name: Fork Rebase
on:
  schedule:
    - cron: '0 12 * * 1'

jobs:
  forkbacon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shitiomatic/forkbacon@master
        with:
          upstream_url: 'https://github.com/auth0/auth0-spa-js.git'
          upstream_branch: 'master'
          branch: 'master'
          method: 'rebase'
          args: ''
